---
version: '2'

services:
  app:
    image: node:10.4-alpine
    volumes:
        - .:/usr/src/app
    ports:
        - "4000:4000"
    working_dir: /usr/src/app
    command: ["npm", "run", "dev"]
    environment:
      - PORT=4000
      - REDIS_URL=redis

  redis:
    image: "redis:latest"
    ports:
        - "6379:6379"

  rediscommander:
      container_name: rediscommander
      hostname: rediscommander
      image: rediscommander/redis-commander:latest
      restart: always
      environment:
      - REDIS_HOSTS=local:redis:6379
      ports:
      - "8082:8081"